import type {Settings,Snapshot} from '../types'
import type {TranslationKey} from '../lib/i18n'
import {icons} from '../components/Icons'
import {MetricCard} from '../components/MetricCard'
import {LatencyChart} from '../components/LatencyChart'
import {TargetTable} from '../components/TargetTable'
const format=(v:number,d=1)=>v>0?v.toFixed(d):'0'
const range=(m:number)=>m===1440?'24h':m===60?'1h':`${m}m`
export function Dashboard({snapshot,settings,busy,onToggle,t}:{snapshot:Snapshot;settings:Settings;busy:boolean;onToggle():Promise<void>;t:(k:TranslationKey)=>string}){const stateKey=(snapshot.connectionState||'stopped') as TranslationKey;return <div className="page"><header className="page-header"><div><span className="eyebrow">{t('realTimeMonitoring').toUpperCase()}</span><h1>{t('dashboard')}</h1><p>{t('allLocal')}</p></div><button className={snapshot.monitoring?'monitor-button stop':'monitor-button'} disabled={busy} onClick={()=>void onToggle()}>{snapshot.monitoring?icons.stop:icons.play}{snapshot.monitoring?t('stop'):t('start')}</button></header><section className={`hero-status state-${snapshot.connectionState}`}><div className="status-orb"><span/></div><div className="hero-copy"><span>{t('status')}</span><h2>{t(stateKey)||snapshot.connectionState}</h2><p>{snapshot.connectionLabel}</p></div><div className="quality-ring" style={{'--score':`${snapshot.qualityScore*3.6}deg`} as React.CSSProperties}><div><strong>{snapshot.qualityScore}</strong><span>{t('quality')}</span></div></div></section><div className="metrics-grid"><MetricCard label={t('latency')} value={format(snapshot.averageLatency)} unit="ms"/><MetricCard label={t('packetLoss')} value={format(snapshot.packetLoss)} unit="%"/><MetricCard label={t('jitter')} value={format(snapshot.jitter)} unit="ms"/><MetricCard label={t('samples')} value={snapshot.samples}/></div><div className="dashboard-grid"><LatencyChart targets={snapshot.targets} eyebrow={t('liveSignal')} title={t('latencyHistory')} rangeLabel={range(settings.graph_range_minutes)}/><TargetTable targets={snapshot.targets} t={t}/></div><section className="panel events-panel"><div className="panel-heading"><div><span className="eyebrow">{t('timeline').toUpperCase()}</span><h2>{t('recentEvents')}</h2></div></div><div className="event-list">{snapshot.recentEvents.length===0&&<div className="empty-list">{t('noEvents')}</div>}{snapshot.recentEvents.slice(0,8).map((event,i)=><article key={`${event.time}-${i}`}><span className={`event-marker ${event.level}`}/><div><strong>{event.message}</strong><small>{new Date(event.time).toLocaleString()}</small></div></article>)}</div></section></div>}
